"""empty message

Revision ID: d59967fa4b6e
Revises: c1f55341a480
Create Date: 2023-07-03 07:38:04.557359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59967fa4b6e'
down_revision = 'c1f55341a480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index('ix_card_image_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=256), nullable=True))
        batch_op.create_index('ix_card_image_url', ['image_url'], unique=False)

    # ### end Alembic commands ###
